[bump]
exclude = [
  "example-migration",
  "example-pinia",
  "example-pinia-mobile",
  "example-pinia-nuxt",
  "example-svelte",
  "example-svelte-runes",
  "example-valtio",
  "example-vanilla",
  "example-vue",
  "example-zustand",
  "playground",
  "tauri-store-cli",
]

[update]
exclude = [
  "@tauri-apps/api",
  "pinia",
  "svelte",
  "tauri-plugin",
  "tokio",
  "valtio",
  "vue",
]
