packages:
  - 'docs'
  - 'examples/migration'
  - 'examples/pinia'
  - 'examples/pinia-nuxt'
  - 'examples/playground'
  - 'examples/svelte'
  - 'examples/svelte-runes'
  - 'examples/valtio'
  - 'examples/vanilla'
  - 'examples/zustand'
  - 'packages/*'
