ignoreWorkspaceRootCheck: true

packages:
  - 'docs'
  - 'examples/migration'
  - 'examples/pinia'
  - 'examples/pinia-mobile'
  - 'examples/pinia-nuxt'
  - 'examples/playground'
  - 'examples/svelte'
  - 'examples/svelte-runes'
  - 'examples/valtio'
  - 'examples/vanilla'
  - 'examples/vue'
  - 'examples/zustand'
  - 'packages/plugin-pinia'
  - 'packages/plugin-svelte'
  - 'packages/plugin-valtio'
  - 'packages/plugin-vue'
  - 'packages/plugin-zustand'
  - 'packages/shared'
  - 'packages/tauri-store'
