packages:
  - 'docs'
  - 'examples/pinia'
  - 'examples/pinia-nuxt'
  - 'examples/shared/javascript'
  - 'examples/shared/pinia'
  - 'examples/shared/react'
  - 'examples/svelte'
  - 'examples/valtio'
  - 'packages/*'
