// THIS FILE WAS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY.
//
// Check the `codegen` command in the `tauri-store-cli` crate.
// https://github.com/ferreira-tb/tauri-store/tree/main/crates/tauri-store-cli
//
// To modify the behavior of the plugin, you must either change the
// upstream `tauri-store` crate or update the code generation itself.
// This ensures that all plugins maintain consistent behavior.

const COMMANDS: &[&str] = &[
  "allow_save",
  "allow_sync",
  "clear_autosave",
  "deny_save",
  "deny_sync",
  "get_default_save_strategy",
  "get_store_collection_path",
  "get_save_strategy",
  "get_store_ids",
  "get_store_path",
  "get_store_state",
  "load",
  "patch",
  "save",
  "save_all",
  "save_all_now",
  "save_now",
  "save_some",
  "save_some_now",
  "set_autosave",
  "set_store_collection_path",
  "set_save_strategy",
  "set_store_options",
  "unload",
];

fn main() {
  tauri_plugin::Builder::new(COMMANDS).build();
}
