// THIS FILE WAS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY.
//
// Check the `codegen` command in the `tauri-store-cli` crate.
// https://github.com/ferreira-tb/tauri-store/tree/main/crates/tauri-store-cli

use tauri::{Runtime, State};
use tauri_store::{Collection, CollectionMarker, StoreCollection};

/// The Zustand plugin.
#[derive(Collection)]
pub struct Zustand<'a, R: Runtime>(pub(crate) State<'a, StoreCollection<R, ZustandMarker>>);

/// Marker for the Zustand plugin.
pub struct ZustandMarker;

impl CollectionMarker for ZustandMarker {}
