const AUTOGENERATED_WARNING: &str = "
// This file was autogenerated and should not be edited manually.
// Check the `codegen` command in the `tauri-store-cli` crate.\n
";

pub fn prepend_autogenerated(contents: &mut String) {
  let warning = AUTOGENERATED_WARNING.trim_start();
  contents.insert_str(0, warning);
}

pub fn remove_nocheck(contents: &mut String) {
  contents
    .replace("// @ts-nocheck", "")
    .trim_start()
    .clone_into(contents);
}
