// THIS FILE WAS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY.
//
// Check the `codegen` command in the `tauri-store-cli` crate.
// https://github.com/ferreira-tb/tauri-store/tree/main/crates/tauri-store-cli

use tauri::{Runtime, State};
use tauri_store::{Collection, CollectionMarker, StoreCollection};

/// The Pinia plugin.
#[derive(Collection)]
pub struct Pinia<'a, R: Runtime>(pub(crate) State<'a, StoreCollection<R, PiniaMarker>>);

/// Marker for the Pinia plugin.
pub struct PiniaMarker;

impl CollectionMarker for PiniaMarker {}
