use super::{Generator, OutputContext};
use crate::path::{assets_dir, package_src_dir};
use crate::target::Target;
use crate::transform::{prepend_autogenerated, remove_nocheck};
use anyhow::Result;
use colored::Colorize;
use std::path::{Path, PathBuf};
use std::time::Instant;

pub(super) fn generate() -> Result<()> {
  let start = Instant::now();
  println!("{}", "generating package code".cyan());

  let assets = assets_plugin_ts_dir();
  generate_commands(&assets)?;

  let duration = start.elapsed();
  println!("{}", format!("done in {duration:?}").green());

  Ok(())
}

fn generate_commands(assets: &Path) -> Result<()> {
  let input = assets.join("commands.ts");
  let output = |ctx: OutputContext<'_>| {
    let dir = package_commands_dir(ctx.target);
    dir.join("autogenerated.ts")
  };

  Generator::builder(&input, &output)
    .transform(&[&remove_nocheck, &prepend_autogenerated])
    .build()
    .generate()
}

fn assets_plugin_ts_dir() -> PathBuf {
  assets_dir().join("plugin-ts")
}

fn package_commands_dir(target: Target) -> PathBuf {
  let mut dir = package_src_dir(target);
  if matches!(target, Target::PluginSvelte) {
    dir.push("lib");
  }

  dir.join("commands")
}
