// THIS FILE WAS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY.
//
// Check the `codegen` command in the `tauri-store-cli` crate.
// https://github.com/ferreira-tb/tauri-store/tree/main/crates/tauri-store-cli
//
// To modify the behavior of the plugin, you must either change the
// upstream `tauri-store` crate or update the code generation itself.
// This ensures that all plugins maintain consistent behavior.

import { commands } from '@tauri-store/shared';

/**
 * Removes one or more stores from the save denylist.
 */
export const allowSave = commands.allowSave('pinia');

/**
 * Removes one or more stores from the sync denylist.
 */
export const allowSync = commands.allowSync('pinia');

/**
 * Stops the autosave.
 */
export const clearAutosave = commands.clearAutosave('pinia');

/**
 * Adds one or more stores to the save denylist.
 */
export const denySave = commands.denySave('pinia');

/**
 * Adds one or more stores to the sync denylist.
 */
export const denySync = commands.denySync('pinia');

/**
 * Gets the default save strategy for the stores.
 * It can be overridden on a per-store basis.
 */
export const getDefaultSaveStrategy = commands.getDefaultSaveStrategy('pinia');

/**
 * Directory where the stores are saved.
 */
export const getStoreCollectionPath = commands.getStoreCollectionPath('pinia');

/**
 * Gets the save strategy used by a store.
 **/
export const getSaveStrategy = commands.getSaveStrategy('pinia');

/**
 * Lists all the store ids.
 */
export const getStoreIds = commands.getStoreIds('pinia');

/**
 * Path where the store is saved.
 **/
export const getStorePath = commands.getStorePath('pinia');

/**
 * Gets the state of a store.
 */
export const getStoreState = commands.getStoreState('pinia');

/**
 * Saves a store to the disk.
 *
 * @example
 * ```ts
 * import { save } from '@tauri-store/pinia';
 *
 * // Save a single store.
 * await save('my-store');
 *
 * // Save some stores.
 * await save('my-store', 'my-store-2');
 * ```
 **/
export const save = commands.save('pinia');

/**
 * Saves all the stores to the disk.
 */
export const saveAll = commands.saveAll('pinia');

/**
 * Saves all the stores to the disk immediately, ignoring the save strategy.
 */
export const saveAllNow = commands.saveAllNow('pinia');

/**
 * Saves a store to the disk immediately, ignoring the save strategy.
 *
 * @example
 * ```ts
 * import { saveNow } from '@tauri-store/pinia';
 *
 * // Save a single store.
 * await saveNow('my-store');
 *
 * // Save some stores.
 * await saveNow('my-store', 'my-store-2');
 * ```
 */
export const saveNow = commands.saveNow('pinia');

/**
 * Saves the stores periodically.
 * @param interval The interval in milliseconds.
 *
 * @example
 * ```ts
 * import { setAutosave } from '@tauri-store/pinia';
 *
 * // Save all the stores every 5 minutes.
 * await setAutosave(5 * 60 * 1000);
 * ```
 */
export const setAutosave = commands.setAutosave('pinia');

/**
 * Sets the save strategy for a store.
 * Calling this will abort any pending save operation.
 *
 * @example
 * ```ts
 * import { setSaveStrategy } from '@tauri-store/pinia';
 *
 * await setSaveStrategy('my-store', 'debounce', 1000);
 * ```
 */
export const setSaveStrategy = commands.setSaveStrategy('pinia');

/**
 * Sets the store options.
 *
 * @example
 * ```ts
 * import { setStoreOptions } from '@tauri-store/pinia';
 *
 * await setStoreOptions('my-store', {
 *  saveOnChange: true,
 *  saveStrategy: 'debounce',
 *  saveInterval: 1000
 * });
 * ```
 */
export const setStoreOptions = commands.setStoreOptions('pinia');

/////////////////////////
// INTERNAL COMMANDS
/////////////////////////

/** @internal */
export const destroy = commands.destroy('pinia');

/** @internal */
export const load = commands.load('pinia');

/** @internal */
export const patch = commands.patch('pinia');

/** @internal */
export const unload = commands.unload('pinia');
