[build]
target-dir = "target"
rustflags = ["--cfg", "tauri_store_tracing"]

[env]
CARGO_TARGET_DIR = "target"

# Workaround to prevent `STATUS_ENTRYPOINT_NOT_FOUND` error in tests.
# See: https://github.com/tauri-apps/tauri/pull/4383#issuecomment-1212221864
__TAURI_STORE_WORKSPACE__ = "true"
