// THIS FILE WAS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY.
//
// Check the `codegen` command in the `tauri-store-cli` crate.
// https://github.com/ferreira-tb/tauri-store/tree/main/crates/tauri-store-cli
//
// To modify the behavior of the plugin, you must either change the
// upstream `tauri-store` crate or update the code generation itself.
// This ensures that all plugins maintain consistent behavior.

import SwiftRs
import Tauri
import UIKit
import WebKit

class VuePlugin: Plugin {
  @objc public func getAppSandboxPath(_ invoke: Invoke) throws {
    if let documentsPath = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first {
      invoke.resolve(["path": documentsPath.path])
    } else {
      invoke.reject("Unable to get sandbox path")
    }
  }

}

@_cdecl("init_plugin_vue")
func initPlugin() -> Plugin {
  return VuePlugin()
}
