// THIS FILE WAS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY.
//
// Check the `codegen` command in the `tauri-store-cli` crate.
// https://github.com/ferreira-tb/tauri-store/tree/main/crates/tauri-store-cli

use tauri::{Runtime, State};
use tauri_store::{Collection, CollectionMarker, StoreCollection};

/// The Valtio plugin.
#[derive(Collection)]
pub struct Valtio<'a, R: Runtime>(pub(crate) State<'a, StoreCollection<R, ValtioMarker>>);

/// Marker for the Valtio plugin.
pub struct ValtioMarker;

impl CollectionMarker for ValtioMarker {}
