// This file was autogenerated and should not be edited manually.
// Check the `codegen` command in the `tauri-store-cli` crate.

use crate::svelte::Svelte;
use tauri::{AppHandle, Manager, Runtime, State, WebviewWindow, Window};

/// Extension for the [`Manager`](https://docs.rs/tauri/latest/tauri/trait.Manager.html)
/// trait providing access to the Svelte plugin.
pub trait ManagerExt<R: Runtime>: Manager<R> {
  /// Returns a handle to the Svelte plugin.
  ///
  /// # Panics
  ///
  /// Panics if the internal [store collection](https://tb.dev.br/tauri-store/rust-docs/tauri_store/struct.StoreCollection.html)
  /// is not in the [resources table](https://docs.rs/tauri/latest/tauri/struct.ResourceTable.html).
  ///
  /// This likely indicates that the method was called before the plugin was properly initialized.
  fn svelte(&self) -> State<Svelte<R>> {
    self.state::<Svelte<R>>()
  }
}

impl<R: Runtime> ManagerExt<R> for AppHandle<R> {}
impl<R: Runtime> ManagerExt<R> for WebviewWindow<R> {}
impl<R: Runtime> ManagerExt<R> for Window<R> {}
