// THIS FILE WAS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY.
//
// Check the `codegen` command in the `tauri-store-cli` crate.
// https://github.com/ferreira-tb/tauri-store/tree/main/crates/tauri-store-cli
//
// To modify the behavior of the plugin, you must either change the
// upstream `tauri-store` crate or update the code generation itself.
// This ensures that all plugins maintain consistent behavior.

use tauri::{Runtime, State};
use tauri_store::{Collection, CollectionMarker, StoreCollection};

/// The Svelte plugin.
#[derive(Collection)]
pub struct Svelte<'a, R: Runtime>(pub(crate) State<'a, StoreCollection<R, SvelteMarker>>);

/// Marker for the Svelte plugin.
pub struct SvelteMarker;

impl CollectionMarker for SvelteMarker {}
