// THIS FILE WAS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY.
//
// Check the `codegen` command in the `tauri-store-cli` crate.
// https://github.com/ferreira-tb/tauri-store/tree/main/crates/tauri-store-cli
//
// To modify the behavior of the plugin, you must either change the
// upstream `tauri-store` crate or update the code generation itself.
// This ensures that all plugins maintain consistent behavior.

package com.plugin.vue

import android.app.Activity
import app.tauri.annotation.Command
import app.tauri.annotation.InvokeArg
import app.tauri.annotation.TauriPlugin
import app.tauri.plugin.JSObject
import app.tauri.plugin.Plugin
import app.tauri.plugin.Invoke

@TauriPlugin
class VuePlugin(private val activity: Activity): Plugin(activity) {

@Command
    fun getAppSandboxPath(invoke: Invoke) {
        // Récupère le chemin vers le répertoire "files" de l'application
        val sandboxPath = activity.filesDir.absolutePath

        val ret = JSObject()
        ret.put("path", sandboxPath)
        invoke.resolve(ret)
    }

}
