// This file was autogenerated and should not be edited manually.

import { commands } from '@tauri-store/shared';

/**
 * Stops the autosave.
 */
export const clearAutosave = commands.clearAutosave('pinia');

/**
 * Gets the default save strategy for the stores.
 * It can be overridden on a per-store basis.
 */
export const getDefaultSaveStrategy = commands.getDefaultSaveStrategy('pinia');

/**
 * Directory where the stores are saved.
 */
export const getPiniaPath = commands.getStoreCollectionPath('pinia');

/**
 * Gets the save strategy used by a store.
 **/
export const getSaveStrategy = commands.getSaveStrategy('pinia');

/**
 * Lists all the store ids.
 */
export const getStoreIds = commands.getStoreIds('pinia');

/**
 * Path where the store is saved.
 **/
export const getStorePath = commands.getStorePath('pinia');

/** Gets the state of a store. */
export const getStoreState = commands.getStoreState('pinia');

/**
 * Saves a store to the disk.
 **/
export const save = commands.save('pinia');

/**
 * Saves all the stores to the disk.
 */
export const saveAll = commands.saveAll('pinia');

/**
 * Saves all the stores to the disk immediately, ignoring the save strategy.
 */
export const saveAllNow = commands.saveAllNow('pinia');

/**
 * Saves a store to the disk immediately, ignoring the save strategy.
 */
export const saveNow = commands.saveNow('pinia');

/**
 * Saves the stores periodically.
 * @param interval The interval in milliseconds.
 */
export const setAutosave = commands.setAutosave('pinia');

/**
 * Sets the save strategy for a store.
 * Calling this will abort any pending save operation.
 */
export const setSaveStrategy = commands.setSaveStrategy('pinia');

/**
 * Sets the store options.
 */
export const setStoreOptions = commands.setStoreOptions('pinia');

/////////////////////////
// INTERNAL COMMANDS
/////////////////////////

/** @internal */
export const load = commands.load('pinia');

/** @internal */
export const patch = commands.patch('pinia');

/** @internal */
export const unload = commands.unload('pinia');
