// This file was autogenerated and should not be edited manually.

import { commands } from '@tauri-store/shared';

/**
 * Abort the autosave.
 */
export const clearAutosave = commands.clearAutosave('pinia');

/**
 * Get the default save strategy for the stores.
 * It can be overridden on a per-store basis.
 */
export const getDefaultSaveStrategy = commands.getDefaultSaveStrategy('pinia');

/**
 * Directory where the stores are saved.
 */
export const getPiniaPath = commands.getStoreCollectionPath('pinia');

/**
 * List all the store ids.
 */
export const getStoreIds = commands.getStoreIds('pinia');

/**
 * Path where the store is saved.
 **/
export const getStorePath = commands.getStorePath('pinia');

/**
 * Get the save strategy used by a store.
 **/
export const getStoreSaveStrategy = commands.getStoreSaveStrategy('pinia');

/** Get the state of a store. */
export const getStoreState = commands.getStoreState('pinia');

/**
 * Save a store to the disk.
 **/
export const save = commands.save('pinia');

/**
 * Save all the stores to the disk.
 */
export const saveAll = commands.saveAll('pinia');

/**
 * Save the stores periodically.
 * @param interval The interval in milliseconds.
 */
export const setAutosave = commands.setAutosave('pinia');

/**
 * Sets the save strategy for a store.
 */
export const setStoreSaveStrategy = commands.setStoreSaveStrategy('pinia');

/////////////////////////
// INTERNAL COMMANDS
/////////////////////////

/** @internal */
export const load = commands.load('pinia');

/** @internal */
export const patch = commands.patch('pinia');

/** @internal */
export const unload = commands.unload('pinia');
