name: Test PR

on:
  pull_request:
    branches: [main]

env:
  RUST_BACKTRACE: 1

concurrency:
  group: test-pr
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Test
        shell: pwsh
        run: scripts/test.ps1 -Ubuntu
