name: Test PR

on:
  pull_request:
    branches: [main]

env:
  RUST_BACKTRACE: 1

concurrency:
  group: test-pr
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libgtk-3-dev libwebkit2gtk-4.1-dev
          pnpm install

      - name: Test
        shell: pwsh
        run: |
          pnpm run type-check
          cargo clippy --workspace
          cargo test -p tauri-store --tests -- --test-threads=1
